# Generated by Django 5.0.3 on 2024-04-06 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_frends_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='frends',
            new_name='friends',
        ),
    ]
